"""empty message

Revision ID: d050ea9ad2a4
Revises: 7324edff39aa
Create Date: 2024-07-04 21:27:07.242329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd050ea9ad2a4'
down_revision = '7324edff39aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('specimen_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specimen_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
